//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostgradoApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class POSTGRADODBEntities : DbContext
    {
        public POSTGRADODBEntities()
            : base("name=POSTGRADODBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TALUMNO> TALUMNO { get; set; }
        public virtual DbSet<TALUMNO_TELEFONO> TALUMNO_TELEFONO { get; set; }
        public virtual DbSet<TDICTAMEN_DEVUELTO> TDICTAMEN_DEVUELTO { get; set; }
        public virtual DbSet<TDICTAMEN_INGRESADO> TDICTAMEN_INGRESADO { get; set; }
        public virtual DbSet<TDOCENTE> TDOCENTE { get; set; }
        public virtual DbSet<TDOCENTE_DOCTORADO> TDOCENTE_DOCTORADO { get; set; }
        public virtual DbSet<TDOCENTE_MAESTRIA> TDOCENTE_MAESTRIA { get; set; }
        public virtual DbSet<TDOCENTE_PROFESION> TDOCENTE_PROFESION { get; set; }
        public virtual DbSet<TDOCENTE_TELEFONO> TDOCENTE_TELEFONO { get; set; }
        public virtual DbSet<TDOCTORADO> TDOCTORADO { get; set; }
        public virtual DbSet<TMAESTRIA> TMAESTRIA { get; set; }
        public virtual DbSet<TPROFESION> TPROFESION { get; set; }
        public virtual DbSet<TUSUARIO> TUSUARIO { get; set; }
        public virtual DbSet<TALUMNO_TELEFONOVIEW> TALUMNO_TELEFONOVIEW { get; set; }
        public virtual DbSet<TALUMNOFULLNAMEVIEW> TALUMNOFULLNAMEVIEW { get; set; }
        public virtual DbSet<TALUMNOVIEW> TALUMNOVIEW { get; set; }
        public virtual DbSet<TDICTAMEN_DEVUELTOVIEW> TDICTAMEN_DEVUELTOVIEW { get; set; }
        public virtual DbSet<TDICTAMEN_INGRESADOVIEW> TDICTAMEN_INGRESADOVIEW { get; set; }
        public virtual DbSet<TDOCENTE_DOCTORADOVIEW> TDOCENTE_DOCTORADOVIEW { get; set; }
        public virtual DbSet<TDOCENTE_MAESTRIAVIEW> TDOCENTE_MAESTRIAVIEW { get; set; }
        public virtual DbSet<TDOCENTE_PROFESIONVIEW> TDOCENTE_PROFESIONVIEW { get; set; }
        public virtual DbSet<TDOCENTE_TELEFONOVIEW> TDOCENTE_TELEFONOVIEW { get; set; }
        public virtual DbSet<TDOCENTEFULLNAMEVIEW> TDOCENTEFULLNAMEVIEW { get; set; }
        public virtual DbSet<TDOCENTEVIEW> TDOCENTEVIEW { get; set; }
        public virtual DbSet<TUSUARIOFULLNAMEVIEW> TUSUARIOFULLNAMEVIEW { get; set; }
        public virtual DbSet<TUSUARIOVIEW> TUSUARIOVIEW { get; set; }
    }
}
