//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostgradoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDICTAMEN_DEVUELTOVIEW
    {
        public int id { get; set; }
        public int Id_de_dictamen { get; set; }
        public string Alumno { get; set; }
        public string Docente { get; set; }
        public string Destinatario { get; set; }
        public bool Apto { get; set; }
        public string Estudio { get; set; }
        public System.DateTime Fecha_de_entrega { get; set; }
        public byte[] Foto_de_dictamen { get; set; }
    }
}
