//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostgradoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDICTAMEN_DEVUELTO
    {
        public int id { get; set; }
        public Nullable<int> id_dictamen { get; set; }
        public string nombre_destinatario { get; set; }
        public string apPaterno_destinatario { get; set; }
        public string apMaterno_destinatario { get; set; }
        public System.DateTime fecha_entrega { get; set; }
        public byte[] foto_dictamen { get; set; }
    
        public virtual TDICTAMEN_INGRESADO TDICTAMEN_INGRESADO { get; set; }
    }
}
