//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostgradoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDOCENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TDOCENTE()
        {
            this.TDICTAMEN_INGRESADO = new HashSet<TDICTAMEN_INGRESADO>();
            this.TDOCENTE_PROFESION = new HashSet<TDOCENTE_PROFESION>();
            this.TDOCENTE_MAESTRIA = new HashSet<TDOCENTE_MAESTRIA>();
            this.TDOCENTE_DOCTORADO = new HashSet<TDOCENTE_DOCTORADO>();
            this.TDOCENTE_TELEFONO = new HashSet<TDOCENTE_TELEFONO>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string apPaterno { get; set; }
        public string apMaterno { get; set; }
        public string telefono_fijo { get; set; }
        public string correo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDICTAMEN_INGRESADO> TDICTAMEN_INGRESADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDOCENTE_PROFESION> TDOCENTE_PROFESION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDOCENTE_MAESTRIA> TDOCENTE_MAESTRIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDOCENTE_DOCTORADO> TDOCENTE_DOCTORADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDOCENTE_TELEFONO> TDOCENTE_TELEFONO { get; set; }
    }
}
